/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.transporter;

import database.TransportManager;
import javax.swing.table.DefaultTableModel;
import ui.manager.UI_DesignFunctions;
import java.sql.*;
/**
 *
 * @author priyankasatish
 */
public class TransportAdminPanel extends javax.swing.JPanel {
    int transporterId = 0;

    /**
     * Creates new form TransportAdminPanel
     */
    public TransportAdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pharmacyAdminName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PharmacyAdminId = new javax.swing.JLabel();
        pharmacyLogo = new javax.swing.JLabel();
        CompanyName = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        manageshipmets = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jTextFieldKeyword = new javax.swing.JTextField();
        btnViewShipments = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ShipmentStatusTable = new javax.swing.JTable();
        jButtonApproveShipment = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        lblOrderID = new javax.swing.JLabel();
        jLabelOrderId = new javax.swing.JLabel();
        btnDistributer = new javax.swing.JButton();

        pharmacyAdminName.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        pharmacyAdminName.setText("Manufacturer Admin");

        jLabel2.setFont(new java.awt.Font("Al Bayan", 0, 24)); // NOI18N
        jLabel2.setText("Welcome");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setText("ID");

        PharmacyAdminId.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        PharmacyAdminId.setText("1001");

        CompanyName.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 2, 13)); // NOI18N
        CompanyName.setText("MANUFACTURE COMPANY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PharmacyAdminId, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pharmacyAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(pharmacyLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(CompanyName)
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pharmacyAdminName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pharmacyLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PharmacyAdminId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(CompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel34.setBorder(javax.swing.BorderFactory.createTitledBorder("SEARCH BY"));

        jTextFieldKeyword.setText("SEARCH ");
        jTextFieldKeyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKeywordActionPerformed(evt);
            }
        });
        jTextFieldKeyword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldKeywordKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jTextFieldKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addComponent(jTextFieldKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        btnViewShipments.setText("VIEW SHIPMENTS");
        btnViewShipments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewShipmentsActionPerformed(evt);
            }
        });

        ShipmentStatusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "2022-10-09", "2", null, "CVA", "5", "pending"},
                {"2", "2022-20-09", "1", null, "CVS", "10", "pending"},
                {"3", "2022-12-09", "1", null, "CVS", "10", "pending"},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "SHIPMENT ID", "ORDER DATE", "DISTRIBUTOR ID", "PHARMACY ID", "PHARMACY NAME", "DELIVERY ADDRESS", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ShipmentStatusTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShipmentStatusTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ShipmentStatusTableMouseEntered(evt);
            }
        });
        ShipmentStatusTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ShipmentStatusTableKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(ShipmentStatusTable);

        jButtonApproveShipment.setText("COMPLETE SHIPMENT");
        jButtonApproveShipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApproveShipmentActionPerformed(evt);
            }
        });

        lblStatus.setText("STATUS");

        jLabelStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 51, 0));
        jLabelStatus.setText("XXX");

        lblOrderID.setText("ORDER ID");

        jLabelOrderId.setText("XXX");

        btnDistributer.setText("PROCEED TO ASSIGN DISTRIBUTOR");
        btnDistributer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDistributerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageshipmetsLayout = new javax.swing.GroupLayout(manageshipmets);
        manageshipmets.setLayout(manageshipmetsLayout);
        manageshipmetsLayout.setHorizontalGroup(
            manageshipmetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageshipmetsLayout.createSequentialGroup()
                .addGroup(manageshipmetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageshipmetsLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDistributer, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageshipmetsLayout.createSequentialGroup()
                        .addGroup(manageshipmetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageshipmetsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnViewShipments, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(manageshipmetsLayout.createSequentialGroup()
                                .addGap(545, 545, 545)
                                .addGroup(manageshipmetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(manageshipmetsLayout.createSequentialGroup()
                                        .addComponent(lblOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(manageshipmetsLayout.createSequentialGroup()
                                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(manageshipmetsLayout.createSequentialGroup()
                                .addGap(512, 512, 512)
                                .addComponent(jButtonApproveShipment, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(manageshipmetsLayout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 969, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        manageshipmetsLayout.setVerticalGroup(
            manageshipmetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageshipmetsLayout.createSequentialGroup()
                .addGroup(manageshipmetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageshipmetsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageshipmetsLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnViewShipments, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(manageshipmetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(manageshipmetsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonApproveShipment, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229)
                .addComponent(btnDistributer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MANAGE SHIPMENTS", manageshipmets);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1328, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldKeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKeywordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldKeywordActionPerformed

    private void jTextFieldKeywordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldKeywordKeyReleased
        String keyword = jTextFieldKeyword.getText();

    }//GEN-LAST:event_jTextFieldKeywordKeyReleased

    private void btnViewShipmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewShipmentsActionPerformed
        UI_DesignFunctions.AlignTableContents(ShipmentStatusTable);
        DefaultTableModel manuOrderTable= (DefaultTableModel)ShipmentStatusTable.getModel();
        manuOrderTable.setRowCount(0);

        try
        {
            ResultSet rs = TransportManager.fetchAllShipments(transporterId);

            while(rs.next())
            {
                int shipmentId = rs.getInt("shipment_id");
                String orderDate = rs.getString("order_date");
                int pharmacyId = rs.getInt("pharmacy_id");
                String pharmacyName = rs.getString("pharmacy_name");
                String distributorName = rs.getString("distributor_name");
                String shipmentStatus = rs.getString("shipment_status");

                Object[] rowData = new Object[7];

                rowData[0] = shipmentId;
                rowData[1] = orderDate;
                rowData[2] = pharmacyId;
                rowData[3] = pharmacyName;
                rowData[4] = distributorName;
                rowData[6] = shipmentStatus;
                manuOrderTable.addRow(rowData);

            }
        }

        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnViewShipmentsActionPerformed

    private void ShipmentStatusTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShipmentStatusTableMouseClicked

    }//GEN-LAST:event_ShipmentStatusTableMouseClicked

    private void ShipmentStatusTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShipmentStatusTableMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ShipmentStatusTableMouseEntered

    private void ShipmentStatusTableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ShipmentStatusTableKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShipmentStatusTableKeyPressed

    private void jButtonApproveShipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApproveShipmentActionPerformed

    }//GEN-LAST:event_jButtonApproveShipmentActionPerformed

    private void btnDistributerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDistributerActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnDistributerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CompanyName;
    private javax.swing.JLabel PharmacyAdminId;
    private javax.swing.JTable ShipmentStatusTable;
    private javax.swing.JButton btnDistributer;
    private javax.swing.JButton btnViewShipments;
    private javax.swing.JButton jButtonApproveShipment;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelOrderId;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldKeyword;
    private javax.swing.JLabel lblOrderID;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel manageshipmets;
    private javax.swing.JLabel pharmacyAdminName;
    private javax.swing.JLabel pharmacyLogo;
    // End of variables declaration//GEN-END:variables
}
